import { Router } from "express";
import { z } from "zod";
import { writeAuditLog } from "../../lib/audit.js";
import { prisma } from "../../lib/prisma.js";
import { requireAuthentication, requirePermissions } from "../auth/auth.middleware.js";

const amount = z.string().regex(/^\d+(\.\d{1,2})?$/);
const invoiceSchema = z.object({ invoiceNumber: z.string().trim().min(2).transform((value) => value.toUpperCase()), clientId: z.string().cuid(), invoiceDate: z.coerce.date(), dueDate: z.coerce.date(), notes: z.string().trim().max(2_000).optional(), items: z.array(z.object({ description: z.string().trim().min(1), quantity: amount, unitPrice: amount })).min(1), vat: amount.optional(), wht: amount.optional() }).refine((value) => value.dueDate >= value.invoiceDate, { path: ["dueDate"], message: "Due date cannot precede invoice date." });
const paymentSchema = z.object({ paymentNumber: z.string().trim().min(2).transform((value) => value.toUpperCase()), clientId: z.string().cuid(), paymentDate: z.coerce.date(), amount, paymentMethod: z.string().trim().min(2), accountId: z.string().cuid(), externalReference: z.string().trim().max(120).optional(), notes: z.string().trim().max(2_000).optional(), allocations: z.array(z.object({ invoiceId: z.string().cuid(), amount })).min(1) });
export const revenueRouter = Router(); revenueRouter.use(requireAuthentication);
revenueRouter.get("/invoices", requirePermissions("invoices.view"), async (_request, response, next) => { try { const invoices = await prisma.invoice.findMany({ include: { client: { select: { name: true } }, allocations: { include: { payment: true } } }, orderBy: { invoiceDate: "desc" } }); response.json(invoices.map(({ allocations, total, ...invoice }) => { const paid = allocations.filter((item) => item.payment.status === "RECORDED").reduce((sum, item) => sum + Number(item.amount), 0); return { ...invoice, total, amountPaid: paid.toFixed(2), balance: (Number(total) - paid).toFixed(2) }; })); } catch (error) { next(error); } });
revenueRouter.post("/invoices", requirePermissions("invoices.create"), async (request, response, next) => { try { const data = invoiceSchema.parse(request.body); const subtotal = data.items.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unitPrice), 0); const vat = Number(data.vat ?? "0"); const wht = Number(data.wht ?? "0"); const invoice = await prisma.invoice.create({ data: { invoiceNumber: data.invoiceNumber, clientId: data.clientId, invoiceDate: data.invoiceDate, dueDate: data.dueDate, notes: data.notes, subtotal: subtotal.toFixed(2), vat: vat.toFixed(2), wht: wht.toFixed(2), total: (subtotal + vat - wht).toFixed(2), items: { create: data.items.map((item) => ({ ...item, amount: (Number(item.quantity) * Number(item.unitPrice)).toFixed(2) })) } } }); await writeAuditLog({ userId: request.auth!.id, action: "CREATE", module: "invoices", recordType: "Invoice", recordId: invoice.id, newValues: { invoiceNumber: data.invoiceNumber } }, request); response.status(201).json(invoice); } catch (error) { next(error); } });
revenueRouter.get("/payments", requirePermissions("payments.view"), async (_request, response, next) => { try { response.json(await prisma.payment.findMany({ include: { client: { select: { name: true } }, account: { select: { name: true } }, allocations: { include: { invoice: { select: { invoiceNumber: true } } } } }, orderBy: { paymentDate: "desc" } })); } catch (error) { next(error); } });
revenueRouter.get("/clients/:clientId/statement", requirePermissions("reports.view"), async (request, response, next) => { try { const clientId = z.string().cuid().parse(request.params.clientId); const client = await prisma.client.findUniqueOrThrow({ where: { id: clientId }, select: { id: true, name: true, code: true } }); const [invoices, payments] = await Promise.all([prisma.invoice.findMany({ where: { clientId, status: { not: "CANCELLED" } }, select: { id: true, invoiceNumber: true, invoiceDate: true, total: true }, orderBy: { invoiceDate: "asc" } }), prisma.payment.findMany({ where: { clientId, status: "RECORDED" }, select: { id: true, paymentNumber: true, paymentDate: true, amount: true, allocations: { select: { invoiceId: true, amount: true } } }, orderBy: { paymentDate: "asc" } })]); const entries = [...invoices.map((invoice) => ({ date: invoice.invoiceDate, type: "INVOICE", reference: invoice.invoiceNumber, debit: Number(invoice.total), credit: 0 })), ...payments.map((payment) => ({ date: payment.paymentDate, type: "PAYMENT", reference: payment.paymentNumber, debit: 0, credit: Number(payment.amount) }))].sort((a, b) => a.date.getTime() - b.date.getTime()); let balance = 0; response.json({ client, entries: entries.map((entry) => ({ ...entry, balance: (balance += entry.debit - entry.credit).toFixed(2) })), closingBalance: balance.toFixed(2) }); } catch (error) { next(error); } });
revenueRouter.post("/payments", requirePermissions("payments.create"), async (request, response, next) => { try { const data = paymentSchema.parse(request.body); const allocated = data.allocations.reduce((sum, item) => sum + Number(item.amount), 0); if (allocated !== Number(data.amount)) throw new z.ZodError([{ code: "custom", path: ["allocations"], message: "Allocations must equal payment amount." }]); const payment = await prisma.$transaction(async (transaction) => { const invoices = await transaction.invoice.findMany({ where: { id: { in: data.allocations.map((item) => item.invoiceId) }, clientId: data.clientId, status: { notIn: ["CANCELLED", "DRAFT"] } }, include: { allocations: { include: { payment: true } } } }); if (invoices.length !== data.allocations.length) throw new Error("Each allocation must target an issued invoice for this client."); for (const allocation of data.allocations) { const invoice = invoices.find((item) => item.id === allocation.invoiceId)!; const balance = Number(invoice.total) - invoice.allocations.filter((item) => item.payment.status === "RECORDED").reduce((sum, item) => sum + Number(item.amount), 0); if (Number(allocation.amount) > balance) throw new Error("Payment allocation exceeds an invoice balance."); } const created = await transaction.payment.create({ data: { paymentNumber: data.paymentNumber, clientId: data.clientId, paymentDate: data.paymentDate, amount: data.amount, paymentMethod: data.paymentMethod, accountId: data.accountId, externalReference: data.externalReference, notes: data.notes, allocations: { create: data.allocations }, } }); await transaction.accountTransaction.create({ data: { accountId: data.accountId, transactionType: "CLIENT_PAYMENT", transactionDate: data.paymentDate, amount: data.amount, direction: "CREDIT", referenceType: "Payment", referenceId: created.id, externalReference: data.externalReference, description: `Client payment ${created.paymentNumber}`, createdById: request.auth!.id } }); return created; }); await writeAuditLog({ userId: request.auth!.id, action: "RECORD", module: "payments", recordType: "Payment", recordId: payment.id, newValues: { paymentNumber: data.paymentNumber } }, request); response.status(201).json(payment); } catch (error) { next(error); } });
revenueRouter.post("/invoices/:invoiceId/issue", requirePermissions("invoices.issue"), async (request, response, next) => { try { const invoice = await prisma.invoice.update({ where: { id: z.string().cuid().parse(request.params.invoiceId), status: "DRAFT" }, data: { status: "ISSUED" } }); await writeAuditLog({ userId: request.auth!.id, action: "ISSUE", module: "invoices", recordType: "Invoice", recordId: invoice.id }, request); response.json(invoice); } catch (error) { next(error); } });
revenueRouter.post("/invoices/:invoiceId/cancel", requirePermissions("invoices.cancel"), async (request, response, next) => { try { const invoice = await prisma.invoice.update({ where: { id: z.string().cuid().parse(request.params.invoiceId), status: { in: ["DRAFT", "ISSUED"] } }, data: { status: "CANCELLED" } }); await writeAuditLog({ userId: request.auth!.id, action: "CANCEL", module: "invoices", recordType: "Invoice", recordId: invoice.id }, request); response.json(invoice); } catch (error) { next(error); } });
revenueRouter.post("/payments/:paymentId/reverse", requirePermissions("payments.reverse"), async (request, response, next) => { try { const payment = await prisma.$transaction(async (transaction) => { const found = await transaction.payment.update({ where: { id: z.string().cuid().parse(request.params.paymentId), status: "RECORDED" }, data: { status: "REVERSED" } }); await transaction.accountTransaction.create({ data: { accountId: found.accountId, transactionType: "REVERSAL", transactionDate: new Date(), amount: found.amount, direction: "DEBIT", referenceType: "Payment", referenceId: found.id, description: `Reversal of payment ${found.paymentNumber}`, createdById: request.auth!.id } }); return found; }); await writeAuditLog({ userId: request.auth!.id, action: "REVERSE", module: "payments", recordType: "Payment", recordId: payment.id }, request); response.json(payment); } catch (error) { next(error); } });
