"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ProtectedPage } from "@/components/protected-page";
import { apiRequest, type AuthSession } from "@/lib/auth";

type AuditLog = { id: string; action: string; module: string; recordType: string; createdAt: string; user: { firstName: string; lastName: string; email: string } | null };
function AuditWorkspace({ session }: { session: AuthSession }) { const [logs, setLogs] = useState<AuditLog[]>([]); const [error, setError] = useState(""); useEffect(() => { apiRequest<AuditLog[]>("/api/admin/audit-logs", session.token).then(setLogs).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Could not load audit logs.")); }, [session.token]); return <AppShell session={session}><section className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f4c20d]">Governance</p><h1 className="mt-1 text-2xl font-semibold">Audit logs</h1><p className="mt-1 text-sm text-white/55">The latest 50 important actions recorded by Securitask.</p>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}<div className="mt-5 overflow-hidden rounded-lg border border-white/15 bg-[#111414]"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-white/[.03] text-xs uppercase text-white/45"><tr><th className="px-4 py-3">When</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Record</th><th className="px-4 py-3">By</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-t border-white/8"><td className="whitespace-nowrap px-4 py-3 text-xs text-white/55">{new Date(log.createdAt).toLocaleString()}</td><td className="px-4 py-3 font-medium text-[#f4c20d]">{log.action}</td><td className="px-4 py-3">{log.module} / {log.recordType}</td><td className="px-4 py-3 text-white/65">{log.user ? `${log.user.firstName} ${log.user.lastName}` : "System"}</td></tr>)}{logs.length === 0 && !error && <tr><td colSpan={4} className="px-4 py-6 text-white/50">No audit records yet.</td></tr>}</tbody></table></div></div></section></AppShell>; }
export default function AuditPage() { return <ProtectedPage>{(session) => <AuditWorkspace session={session} />}</ProtectedPage>; }
