"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ProtectedPage } from "@/components/protected-page";
import { demoEmployees, demoPayrollRuns } from "@/lib/demo-data";

export default function PayrollDetailPage() {
  const { payrollId } = useParams<{ payrollId: string }>();
  const run = demoPayrollRuns.find((item) => item.id === payrollId);
  return <ProtectedPage>{(session) => <AppShell session={session}>{!run ? <section className="mt-10"><h1 className="text-3xl font-semibold">Payroll run not found</h1><Link href="/payroll" className="mt-5 inline-block text-[#f4c20d]">Return to payroll</Link></section> : <section className="mt-10"><Link href="/payroll" className="text-sm text-white/55 transition hover:text-[#f4c20d]">← Back to payroll</Link><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#f4c20d]">Payroll run</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{run.name}</h1><p className="mt-3 text-sm text-white/55">{run.period}</p></div><button className="rounded-lg bg-[#f4c20d] px-4 py-3 text-sm font-bold text-[#0d0d0d]">Mark paid</button></div><div className="mt-8 rounded-xl border border-white/10 bg-[#1f1f1f]"><div className="border-b border-white/10 p-5"><p className="text-sm text-white/50">Total net pay</p><p className="mt-2 text-3xl font-semibold text-[#f4c20d]">{run.totalNetPay}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wide text-white/40"><tr><th className="px-5 py-4 font-medium">Employee</th><th className="px-5 py-4 font-medium">Basic</th><th className="px-5 py-4 font-medium">Allowances</th><th className="px-5 py-4 font-medium">Overtime</th><th className="px-5 py-4 font-medium">Deductions</th><th className="px-5 py-4 font-medium">Advance recovery</th><th className="px-5 py-4 font-medium">Net pay</th></tr></thead><tbody>{run.lines.map((line) => <tr key={line.employeeId} className="border-b border-white/5 last:border-0"><td className="px-5 py-4 font-medium">{demoEmployees.find((employee) => employee.id === line.employeeId)?.fullName}</td><td className="px-5 py-4 text-white/60">{line.basicSalary}</td><td className="px-5 py-4 text-white/60">{line.allowances}</td><td className="px-5 py-4 text-white/60">{line.overtime}</td><td className="px-5 py-4 text-white/60">{line.deductions}</td><td className="px-5 py-4 text-white/60">{line.advanceRecovery}</td><td className="px-5 py-4 font-semibold text-[#f4c20d]">{line.netPay}</td></tr>)}{run.lines.length === 0 && <tr><td colSpan={7} className="px-5 py-12 text-center text-white/50">Line details are not included for this demo payroll run.</td></tr>}</tbody></table></div></div></section>}</AppShell>}</ProtectedPage>;
}
