"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ProtectedPage } from "@/components/protected-page";
import { apiRequest, type AuthSession } from "@/lib/auth";
type Employee = { employeeNumber: string; firstName: string; lastName: string; phone: string; email: string | null; jobTitle: string; employeeType: string; basicSalary: string; status: string; dateJoined: string; assignedSite: { name: string; code: string; client: { name: string } } | null };
function Detail({ session }: { session: AuthSession }) { const { employeeId } = useParams<{ employeeId: string }>(); const [employee, setEmployee] = useState<Employee | null>(null); const [error, setError] = useState(""); useEffect(() => { apiRequest<Employee>(`/api/employees/${employeeId}`, session.token).then(setEmployee).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Employee not found.")); }, [employeeId, session.token]); if (!employee) return <AppShell session={session}><section className="mx-auto max-w-5xl py-12 text-white/55">{error || "Loading employee..."}</section></AppShell>; return <AppShell session={session}><section className="mx-auto max-w-5xl space-y-5"><Link href="/employees" className="text-sm text-white/55 hover:text-[#f4c20d]">← Back to employees</Link><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f4c20d]">{employee.employeeNumber}</p><h1 className="mt-1 text-2xl font-semibold">{employee.firstName} {employee.lastName}</h1><p className="mt-1 text-sm text-white/55">{employee.jobTitle} · {employee.employeeType.replace("_", " ")}</p></header><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-lg border border-white/15 bg-[#111414] p-5"><h2 className="font-semibold">Employment details</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-white/45">Basic salary</dt><dd className="mt-1 font-semibold text-[#f4c20d]">MWK {Number(employee.basicSalary).toLocaleString()}</dd></div><div><dt className="text-white/45">Status</dt><dd className="mt-1">{employee.status}</dd></div><div><dt className="text-white/45">Date joined</dt><dd className="mt-1">{new Date(employee.dateJoined).toLocaleDateString()}</dd></div></dl></article><article className="rounded-lg border border-white/15 bg-[#111414] p-5"><h2 className="font-semibold">Contact & assignment</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-white/45">Phone</dt><dd className="mt-1">{employee.phone}</dd></div><div><dt className="text-white/45">Email</dt><dd className="mt-1">{employee.email ?? "Not recorded"}</dd></div><div><dt className="text-white/45">Current site</dt><dd className="mt-1">{employee.assignedSite ? `${employee.assignedSite.client.name} — ${employee.assignedSite.name}` : "No site assigned"}</dd></div></dl></article></div><p className="rounded-md border border-[#f4c20d]/20 bg-[#f4c20d]/5 p-3 text-sm text-white/65">Basic salary is used when preparing payroll. This page does not send or initiate any payment.</p></section></AppShell>; }
export default function EmployeeDetailPage() { return <ProtectedPage>{(session) => <Detail session={session} />}</ProtectedPage>; }
