"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ProtectedPage } from "@/components/protected-page";
import { apiRequest, type AuthSession } from "@/lib/auth";

type Summary = { currency: string; bankBalance: number; cashBalance: number; totalReceived: number; totalExpenses: number; outstandingInvoices: number; payrollDue: number; outstandingAdvances: number; netProfit: number; cashFlow: { label: string; amount: number }[]; expenseCategories: { name: string; amount: number }[] };
const formatMoney = (amount: number, currency: string) => `${currency} ${amount.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;

function Dashboard({ session }: { session: AuthSession }) {
  const [summary, setSummary] = useState<Summary | null>(null); const [error, setError] = useState("");
  useEffect(() => { apiRequest<Summary>("/api/dashboard/summary", session.token).then(setSummary).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Could not load dashboard data.")); }, [session.token]);
  const cards = summary ? [{ label: "Bank Balance", value: summary.bankBalance, href: "/accounts" }, { label: "Cash Balance", value: summary.cashBalance, href: "/accounts" }, { label: "Total Received", value: summary.totalReceived, href: "/payments" }, { label: "Total Expenses", value: summary.totalExpenses, href: "/expenses" }, { label: "Outstanding Invoices", value: summary.outstandingInvoices, href: "/invoices" }, { label: "Payroll Due", value: summary.payrollDue, href: "/payroll" }, { label: "Outstanding Advances", value: summary.outstandingAdvances, href: "/advances" }, { label: "Net Profit", value: summary.netProfit, href: "/reports" }] : [];
  const categoryTotal = summary?.expenseCategories.reduce((total, item) => total + item.amount, 0) ?? 0;
  return <AppShell session={session}><section className="mx-auto max-w-7xl"><p className="py-1 text-sm font-bold uppercase tracking-tight text-[#f4c20d]">Dashboard</p>{error && <p className="mt-4 rounded-md border border-red-400/30 bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p>}<div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{summary ? cards.map((card) => <Link key={card.label} href={card.href} className="rounded-lg border border-white/15 bg-[linear-gradient(145deg,#151818,#101212)] p-4 transition hover:border-[#f4c20d]/60"><p className="text-xs text-white/60">{card.label}</p><p className="mt-3 text-xl font-semibold">{formatMoney(card.value, summary.currency)}</p><p className="mt-2 text-xs text-[#f4c20d]">View details ›</p></Link>) : Array.from({ length: 8 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-lg border border-white/10 bg-white/[.06]" />)}</div><div className="mt-4 grid gap-3 xl:grid-cols-[1.45fr_.85fr]"><article className="rounded-lg border border-white/15 bg-[#1f1f1f] p-4"><h2 className="text-sm font-semibold">Cash Flow Overview</h2>{summary ? <div className="mt-5 grid grid-cols-6 gap-2 items-end h-36">{summary.cashFlow.map((item) => <div key={item.label} className="flex h-full flex-col justify-end text-center"><div className="rounded-t bg-[#f4c20d]" style={{ height: `${Math.max(5, Math.min(100, Math.abs(item.amount) / Math.max(1, ...summary.cashFlow.map((flow) => Math.abs(flow.amount))) * 100))}%` }} /><span className="mt-2 text-[10px] text-white/50">{item.label}</span></div>)}</div> : <div className="mt-4 h-36 animate-pulse rounded bg-white/[.06]" />}</article><article className="rounded-lg border border-white/15 bg-[#1f1f1f] p-4"><h2 className="text-sm font-semibold">Expense by Category</h2>{summary ? <div className="mt-4 space-y-3">{summary.expenseCategories.length ? summary.expenseCategories.map((item) => <div key={item.name}><div className="flex justify-between text-xs"><span>{item.name}</span><span className="text-[#f4c20d]">{categoryTotal ? Math.round(item.amount / categoryTotal * 100) : 0}%</span></div><div className="mt-1 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#f4c20d]" style={{ width: `${categoryTotal ? item.amount / categoryTotal * 100 : 0}%` }} /></div></div>) : <p className="py-7 text-sm text-white/50">No paid expenses yet.</p>}</div> : <div className="mt-4 h-36 animate-pulse rounded bg-white/[.06]" />}</article></div></section></AppShell>;
}

export default function DashboardPage() { return <ProtectedPage>{(session) => <Dashboard session={session} />}</ProtectedPage>; }
